---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: deployment
        image: nginx:latest
        ports: 
        - containerPort: 80
