---
- name: install minikube
  hosts: localhost
  become: yes
  tasks:
    - name: Install docker
      yum:
        name: docker
        state: present
     # notify: start docker
     # handlers:
    - name: start docker
      service:
        name: docker
        state: started
    - name: Setup repo for kubectl
      yum_repository:
        name: Kubernetes
        description: Kubectl
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgcheck: yes
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        repo_gpgcheck: yes
    - name: Download kubectl binary
      get_url:
        url: https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.6/2022-03-09/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: 0755
    - name: Verify kubectl installation
      command: kubectl version --client
      register: kubectl_version

    - name: Install conntrack
      yum:
        name: conntrack
        state: present
    - name: Download minikube package
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/
        mode: 0755

    - name: Start Minikube
      command: sudo install minikube-linux-amd64 /usr/local/bin/minikube
